name: Build
on:
  push:
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Check out source code
        uses: actions/checkout@v4

      - name: Build
        run: cd frontend && yarn && yarn build

      - name: Tests
        run: cd frontend && yarn test
